name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:latest-debian
    timeout-minutes: 10

    steps:
      - name: Lint the Dockerfile
        run: hadolint Dockerfile
